### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by kalpesh-maru** [semagnum/shot_matcher#30]
I an unable to install this addon, I tried installing build.py, __init__.py with no luck, the link on installation guide does not work

**Comment by semagnum** [comment]
I'm so sorry, I don't know why my notifications didn't catch this. You should be installing it as a .zip file, not any single file.

![image](https://github.com/user-attachments/assets/f05346de-3c40-4ed2-83a5-e78a5ef1cbfb)

If the zip file installation fails, send me the error message and I can take a look. I'll give a week to troubleshoot before assuming I dropped the ball on this and closing the ticket.

**Comment by semagnum** [comment]
Frankly I should update or remove my Shot Matcher docs because installation is more straightforward and documented. I can just put usage in the README instead.

**Comment by semagnum** [comment]
Fixed the README in 674317ed3039ccf679ddf43e3cabe10a7de0536f and b25012e8ff18ba85f4518745251b5cf16460ead4 so they include usage, previously documented on the site. Just to simplify it on GitHub.

And again, for those new to downloading and installing add-ons: for single `.py` files, install it directly. This add-on is multiple files, and so download Shot Matcher as a `.zip` file (extensions in 4.2 must also be `.zip` files). You can install `.zip` files directly into Blender, which will copy all the files in. If there's errors upon installation, it may be the add-on's fault. You can create a new issue and copy-and-paste the error message here.

Closing since it's been a week with no update.
